### ISSUE TITLE
Update labels of various plugin settings

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#6] opened 2017-01-20 06:15 UTC
![image](https://cloud.githubusercontent.com/assets/24661377/22233322/6effd6d8-e23f-11e6-912a-e29466029d74.png)

* please remove '(Do not adjust unless instructed to by Oxipay staff)' from 'Gateway URL' description

* please change 'Gateway URL Sanbox' to 'Test Gateway URL'

* please change 'Merchant Number' to 'Merchant ID'

**Comment by blueninja2** [comment] 2017-02-20 05:27
Hi,

Looks good, the only issue outstanding is the **Merchant Number**, please change this to **Merchant ID**.

**Comment by blueninja2** [comment] 2017-03-08 04:47
Thanks, I can see it now as Merchant ID. However, I've noticed that the value in Merchant ID is masked. Are we able to change it so that it is visible. The only value that needs to be masked is the API Key.

![image](https://cloud.githubusercontent.com/assets/22509613/23690539/57e771aa-0412-11e7-993a-05104e28dfcf.png)

**Comment by iugo-josh** [comment] 2017-03-08 23:16
I've added a commit to PR #21 that will change the Merchant ID to a plain text field.

You may need to clear out the cache for this to appear in the admin.

An existing value in the field may appear strangely at first, as the old field type was encrypting the value in this field. Saving a new merchant ID in plain text will fix this.

**Comment by blueninja2** [comment] 2017-03-20 01:07
Have tested this on a fresh bitnami/magento image and the issue is still ocuring. Have also cleared the browser's cache and also flushed Magento's cache and yeah, the Merchant ID is still masked.

Will move this issue into the backlog column.

**Comment by blueninja2** [comment] 2017-03-20 01:29
In the second PR that was submitted, the issue is resolved and I can see that the merchant ID is no longer masked.
Closing this issue off.

**Closed by blueninja2** 2017-03-20 01:29 UTC
