### ISSUE TITLE
Stock is not decremented for Oxipay purchases.

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#5] opened 2017-01-20 06:07 UTC
![image](https://cloud.githubusercontent.com/assets/24661377/22233340/996d74a2-e23f-11e6-8426-b398943a29e0.png)

However, it is for Check/Money Order purchases.

**Comment by blueninja2** [comment] 2017-02-21 01:19
Hi,

I have re-tested this and the issue is still occuring.

Here I have created a new product - iPhone 6 - with a quantity of 100. Put an order for about 11 of them but after the transaction successfully went through Oxipay; it still shows 100 for the quantity - i.e. it was not decremented by 11 as expected.

![image](https://cloud.githubusercontent.com/assets/22509613/23147000/9ebdfcea-f82b-11e6-80d9-14e6853c2d9a.png)

**Comment by blueninja2** [comment] 2017-05-10 04:16
Sam to follow up on this one.

**Comment by esteban-terem** [comment] 2017-05-10 05:22
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).

**Closed** 2018-01-30 03:02 UTC
