### ISSUE TITLE
Incorrect plugin default values

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#3] opened 2017-01-20 06:03 UTC
![image](https://cloud.githubusercontent.com/assets/24661377/22233374/e2615426-e23f-11e6-8010-adbcf8e83af5.png)

* The 'Gateway URL' field is set with the Sandbox URL; it should be: https://secure.oxipay.com.au/Checkout?platform=default
* The 'Test Gateway URL' should be: https://xpozsecure.certegyezipay.com.au/Checkout?platform=default
* Test Mode is set to enabled

**Comment by blueninja2** [comment] 2017-02-20 05:26
Hi,

The issue is still occurring:

Gateway URL has **https://xpozsecure.certegyezipay.com.au/Checkout?platform=Magento** 
Test Gateway URL has **https://xpozsecure.certegyezipay.com.au/Checkout?platform=Magento**

Can you please change this so that:

Gateway URL has **https://secure.oxipay.com.au/Checkout?platform=Default**
Test Gateway URL has **https://securesandbox.oxipay.com.au/Checkout?platform=Default**

**Comment by blueninja2** [comment] 2017-03-08 04:50
Test Mode is now set to Yes. I'll move this issue to the done column and then close it off once the PR is reviewed and approved.

**Comment by blueninja2** [comment] 2017-03-20 00:24
Tested and passed. As part of issue #16 we will be requesting that the test mode drop-down be removed. However, this does not affect this issue which I will be closing off.

**Closed by blueninja2** 2017-03-20 00:24 UTC
