### ISSUE TITLE
Oxipay Order numbers

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#9] opened 2017-01-23 05:16 UTC
![image](https://cloud.githubusercontent.com/assets/24661377/22233239/e0e8df66-e23e-11e6-8758-c0da6c2a189b.png)

After an Oxipay transaction is processed, it is not visible in 'Magento > Sales > Orders'.
Although 'Check/MoneyOrder' transactions are.
This also seems to be affecting the Order number that is associated with Oxipay transactions, as consecutive Oxipay transactions display the same Order number in the Oxipay email confirmation.
The Oxipay Order number only increases after a Check/MoneyOrder transaction is processed.

**Comment by blueninja2** [comment] 2017-02-21 01:26
I have re-tested this and the issue is still occuring - as you can see from the screenshots below; the timestamps for the three transactions are different however the order number is not being incremented (remains at 4).

![image](https://cloud.githubusercontent.com/assets/22509613/23147178/c8f6c734-f82c-11e6-8d58-400ece0bfa66.png)

![image](https://cloud.githubusercontent.com/assets/22509613/23147179/cce6c6a0-f82c-11e6-806d-ce2324184e78.png)

![image](https://cloud.githubusercontent.com/assets/22509613/23147182/cf9a1dde-f82c-11e6-8520-60d49720544a.png)

**Comment by blueninja2** [comment] 2017-05-10 04:10
Sam/Tao to investigate this issue further and if its still an issue with the new plugin code.

**Comment by esteban-terem** [comment] 2017-05-10 05:23
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).

**Closed** 2017-05-10 06:56 UTC
